exclude: '^docs/|/migrations/|devcontainer.json'
default_stages: [commit]

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.16.0'
    hooks:
      - id: django-upgrade
        args: ['--target-version', '4.2']

  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      # Linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Formatter
      - id: ruff-format

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django

  - repo: local
    hooks:
      - id: pytest
        name: Run tests
        entry: pytest
        language: system
        args: [ "-m", "not skip", "-p", "no:warnings" ]
        verbose: true
        pass_filenames: false
        stages: [ pre-commit, pre-push ]
        fail_fast: true

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.21.3
    hooks:
      - id: commitizen
        entry: cz
        args: [ 'check', '--commit-msg-file', '.git/COMMIT_EDITMSG' ]
        pass_filenames: false
        stages: [ commit-msg ]


# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
