version: '3'

services:
  docs:
    image: tc_chat_local_docs
    container_name: tc_chat_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    environment:
      DJANGO_READ_DOT_ENV_FILE: "False"
      DOCS_SQLITE_DB_SWITCH: "True"
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./tc_chat:/app/tc_chat:z
    ports:
      - '9000:9000'
    command: /start-docs
