version: '3'

volumes:
  tc_chat_local_postgres_data: {}
  tc_chat_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: tc_chat_local_django
    container_name: tc_chat_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '80:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: tc_chat_production_postgres
    container_name: tc_chat_local_postgres
    volumes:
      - tc_chat_local_postgres_data:/var/lib/postgresql/data
      - tc_chat_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: docker.io/redis:6
    container_name: tc_chat_local_redis

  celeryworker:
    <<: *django
    image: tc_chat_local_celeryworker
    container_name: tc_chat_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: tc_chat_local_celerybeat
    container_name: tc_chat_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: tc_chat_local_flower
    container_name: tc_chat_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
